// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/adapters/protobuf/trips/trips.proto

package trips

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"

	sro "github.com/de4et/flight-booking/internal/adapters/protobuf/sro"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           string                 `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	Tid           string                 `protobuf:"bytes,2,opt,name=tid,proto3" json:"tid,omitempty"`
	Sid           string                 `protobuf:"bytes,3,opt,name=sid,proto3" json:"sid,omitempty"`
	CacheId       string                 `protobuf:"bytes,4,opt,name=cache_id,json=cacheId,proto3" json:"cache_id,omitempty"`
	Provider      *Provider              `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	Segments      []*TripSegment         `protobuf:"bytes,6,rep,name=segments,proto3" json:"segments,omitempty"`
	Prices        *TripPrices            `protobuf:"bytes,7,opt,name=prices,proto3" json:"prices,omitempty"`
	Rules         *FareRules             `protobuf:"bytes,8,opt,name=rules,proto3" json:"rules,omitempty"`
	Metadata      *TripMetadata          `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Booking       *TripBooking           `protobuf:"bytes,10,opt,name=booking,proto3" json:"booking,omitempty"`
	Sro           *sro.SRO               `protobuf:"bytes,11,opt,name=sro,proto3" json:"sro,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trip) Reset() {
	*x = Trip{}
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trip) ProtoMessage() {}

func (x *Trip) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trip.ProtoReflect.Descriptor instead.
func (*Trip) Descriptor() ([]byte, []int) {
	return file_internal_adapters_protobuf_trips_trips_proto_rawDescGZIP(), []int{0}
}

func (x *Trip) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *Trip) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *Trip) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *Trip) GetCacheId() string {
	if x != nil {
		return x.CacheId
	}
	return ""
}

func (x *Trip) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *Trip) GetSegments() []*TripSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *Trip) GetPrices() *TripPrices {
	if x != nil {
		return x.Prices
	}
	return nil
}

func (x *Trip) GetRules() *FareRules {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *Trip) GetMetadata() *TripMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Trip) GetBooking() *TripBooking {
	if x != nil {
		return x.Booking
	}
	return nil
}

func (x *Trip) GetSro() *sro.SRO {
	if x != nil {
		return x.Sro
	}
	return nil
}

type TripSegment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FlightNumber     string                 `protobuf:"bytes,1,opt,name=flight_number,json=flightNumber,proto3" json:"flight_number,omitempty"`
	Carrier          string                 `protobuf:"bytes,2,opt,name=carrier,proto3" json:"carrier,omitempty"`
	OperatingCarrier string                 `protobuf:"bytes,3,opt,name=operating_carrier,json=operatingCarrier,proto3" json:"operating_carrier,omitempty"`
	Departure        *FlightPoint           `protobuf:"bytes,4,opt,name=departure,proto3" json:"departure,omitempty"`
	Arrival          *FlightPoint           `protobuf:"bytes,5,opt,name=arrival,proto3" json:"arrival,omitempty"`
	DurationMinutes  int32                  `protobuf:"varint,6,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	CabinClass       string                 `protobuf:"bytes,7,opt,name=cabin_class,json=cabinClass,proto3" json:"cabin_class,omitempty"`
	FareCode         string                 `protobuf:"bytes,8,opt,name=fare_code,json=fareCode,proto3" json:"fare_code,omitempty"`
	Baggage          *BaggageInfo           `protobuf:"bytes,9,opt,name=baggage,proto3" json:"baggage,omitempty"`
	Meal             string                 `protobuf:"bytes,10,opt,name=meal,proto3" json:"meal,omitempty"`
	Aircraft         string                 `protobuf:"bytes,11,opt,name=aircraft,proto3" json:"aircraft,omitempty"`
	StopTimeMinutes  int32                  `protobuf:"varint,12,opt,name=stop_time_minutes,json=stopTimeMinutes,proto3" json:"stop_time_minutes,omitempty"`
	Direction        int32                  `protobuf:"varint,13,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TripSegment) Reset() {
	*x = TripSegment{}
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripSegment) ProtoMessage() {}

func (x *TripSegment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripSegment.ProtoReflect.Descriptor instead.
func (*TripSegment) Descriptor() ([]byte, []int) {
	return file_internal_adapters_protobuf_trips_trips_proto_rawDescGZIP(), []int{1}
}

func (x *TripSegment) GetFlightNumber() string {
	if x != nil {
		return x.FlightNumber
	}
	return ""
}

func (x *TripSegment) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *TripSegment) GetOperatingCarrier() string {
	if x != nil {
		return x.OperatingCarrier
	}
	return ""
}

func (x *TripSegment) GetDeparture() *FlightPoint {
	if x != nil {
		return x.Departure
	}
	return nil
}

func (x *TripSegment) GetArrival() *FlightPoint {
	if x != nil {
		return x.Arrival
	}
	return nil
}

func (x *TripSegment) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *TripSegment) GetCabinClass() string {
	if x != nil {
		return x.CabinClass
	}
	return ""
}

func (x *TripSegment) GetFareCode() string {
	if x != nil {
		return x.FareCode
	}
	return ""
}

func (x *TripSegment) GetBaggage() *BaggageInfo {
	if x != nil {
		return x.Baggage
	}
	return nil
}

func (x *TripSegment) GetMeal() string {
	if x != nil {
		return x.Meal
	}
	return ""
}

func (x *TripSegment) GetAircraft() string {
	if x != nil {
		return x.Aircraft
	}
	return ""
}

func (x *TripSegment) GetStopTimeMinutes() int32 {
	if x != nil {
		return x.StopTimeMinutes
	}
	return 0
}

func (x *TripSegment) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

type FlightPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Airport       string                 `protobuf:"bytes,1,opt,name=airport,proto3" json:"airport,omitempty"`
	Terminal      string                 `protobuf:"bytes,2,opt,name=terminal,proto3" json:"terminal,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightPoint) Reset() {
	*x = FlightPoint{}
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightPoint) ProtoMessage() {}

func (x *FlightPoint) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightPoint.ProtoReflect.Descriptor instead.
func (*FlightPoint) Descriptor() ([]byte, []int) {
	return file_internal_adapters_protobuf_trips_trips_proto_rawDescGZIP(), []int{2}
}

func (x *FlightPoint) GetAirport() string {
	if x != nil {
		return x.Airport
	}
	return ""
}

func (x *FlightPoint) GetTerminal() string {
	if x != nil {
		return x.Terminal
	}
	return ""
}

func (x *FlightPoint) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type BaggageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pieces        int32                  `protobuf:"varint,1,opt,name=pieces,proto3" json:"pieces,omitempty"`
	Weight        int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaggageInfo) Reset() {
	*x = BaggageInfo{}
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaggageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaggageInfo) ProtoMessage() {}

func (x *BaggageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaggageInfo.ProtoReflect.Descriptor instead.
func (*BaggageInfo) Descriptor() ([]byte, []int) {
	return file_internal_adapters_protobuf_trips_trips_proto_rawDescGZIP(), []int{3}
}

func (x *BaggageInfo) GetPieces() int32 {
	if x != nil {
		return x.Pieces
	}
	return 0
}

func (x *BaggageInfo) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *BaggageInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type TripPrices struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Price                  float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	SearchPrice            float64                `protobuf:"fixed64,2,opt,name=search_price,json=searchPrice,proto3" json:"search_price,omitempty"`
	PriceFare              float64                `protobuf:"fixed64,3,opt,name=price_fare,json=priceFare,proto3" json:"price_fare,omitempty"`
	ProviderServiceFee     float64                `protobuf:"fixed64,4,opt,name=provider_service_fee,json=providerServiceFee,proto3" json:"provider_service_fee,omitempty"`
	ProviderTaxesAmount    float64                `protobuf:"fixed64,5,opt,name=provider_taxes_amount,json=providerTaxesAmount,proto3" json:"provider_taxes_amount,omitempty"`
	ProviderCurrency       string                 `protobuf:"bytes,6,opt,name=provider_currency,json=providerCurrency,proto3" json:"provider_currency,omitempty"`
	MinAllowablePrice      float64                `protobuf:"fixed64,7,opt,name=min_allowable_price,json=minAllowablePrice,proto3" json:"min_allowable_price,omitempty"`
	TkpTax                 float64                `protobuf:"fixed64,8,opt,name=tkp_tax,json=tkpTax,proto3" json:"tkp_tax,omitempty"`
	SpecTax                float64                `protobuf:"fixed64,9,opt,name=spec_tax,json=specTax,proto3" json:"spec_tax,omitempty"`
	PricerInfo             *PricerInfo            `protobuf:"bytes,10,opt,name=pricer_info,json=pricerInfo,proto3" json:"pricer_info,omitempty"`
	BagsPrice              float64                `protobuf:"fixed64,11,opt,name=bags_price,json=bagsPrice,proto3" json:"bags_price,omitempty"`
	PassengersPriceDetails map[string]float64     `protobuf:"bytes,12,rep,name=passengers_price_details,json=passengersPriceDetails,proto3" json:"passengers_price_details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TripPrices) Reset() {
	*x = TripPrices{}
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripPrices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripPrices) ProtoMessage() {}

func (x *TripPrices) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripPrices.ProtoReflect.Descriptor instead.
func (*TripPrices) Descriptor() ([]byte, []int) {
	return file_internal_adapters_protobuf_trips_trips_proto_rawDescGZIP(), []int{4}
}

func (x *TripPrices) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TripPrices) GetSearchPrice() float64 {
	if x != nil {
		return x.SearchPrice
	}
	return 0
}

func (x *TripPrices) GetPriceFare() float64 {
	if x != nil {
		return x.PriceFare
	}
	return 0
}

func (x *TripPrices) GetProviderServiceFee() float64 {
	if x != nil {
		return x.ProviderServiceFee
	}
	return 0
}

func (x *TripPrices) GetProviderTaxesAmount() float64 {
	if x != nil {
		return x.ProviderTaxesAmount
	}
	return 0
}

func (x *TripPrices) GetProviderCurrency() string {
	if x != nil {
		return x.ProviderCurrency
	}
	return ""
}

func (x *TripPrices) GetMinAllowablePrice() float64 {
	if x != nil {
		return x.MinAllowablePrice
	}
	return 0
}

func (x *TripPrices) GetTkpTax() float64 {
	if x != nil {
		return x.TkpTax
	}
	return 0
}

func (x *TripPrices) GetSpecTax() float64 {
	if x != nil {
		return x.SpecTax
	}
	return 0
}

func (x *TripPrices) GetPricerInfo() *PricerInfo {
	if x != nil {
		return x.PricerInfo
	}
	return nil
}

func (x *TripPrices) GetBagsPrice() float64 {
	if x != nil {
		return x.BagsPrice
	}
	return 0
}

func (x *TripPrices) GetPassengersPriceDetails() map[string]float64 {
	if x != nil {
		return x.PassengersPriceDetails
	}
	return nil
}

type PricerInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Markup              float64                `protobuf:"fixed64,1,opt,name=markup,proto3" json:"markup,omitempty"`
	Commission          float64                `protobuf:"fixed64,2,opt,name=commission,proto3" json:"commission,omitempty"`
	PartnerAffiliateFee float64                `protobuf:"fixed64,3,opt,name=partner_affiliate_fee,json=partnerAffiliateFee,proto3" json:"partner_affiliate_fee,omitempty"`
	CashbackRate        float64                `protobuf:"fixed64,4,opt,name=cashback_rate,json=cashbackRate,proto3" json:"cashback_rate,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PricerInfo) Reset() {
	*x = PricerInfo{}
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricerInfo) ProtoMessage() {}

func (x *PricerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricerInfo.ProtoReflect.Descriptor instead.
func (*PricerInfo) Descriptor() ([]byte, []int) {
	return file_internal_adapters_protobuf_trips_trips_proto_rawDescGZIP(), []int{5}
}

func (x *PricerInfo) GetMarkup() float64 {
	if x != nil {
		return x.Markup
	}
	return 0
}

func (x *PricerInfo) GetCommission() float64 {
	if x != nil {
		return x.Commission
	}
	return 0
}

func (x *PricerInfo) GetPartnerAffiliateFee() float64 {
	if x != nil {
		return x.PartnerAffiliateFee
	}
	return 0
}

func (x *PricerInfo) GetCashbackRate() float64 {
	if x != nil {
		return x.CashbackRate
	}
	return 0
}

type Provider struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Gds               string                 `protobuf:"bytes,2,opt,name=gds,proto3" json:"gds,omitempty"`
	GdsServer         string                 `protobuf:"bytes,3,opt,name=gds_server,json=gdsServer,proto3" json:"gds_server,omitempty"`
	OfficeId          string                 `protobuf:"bytes,4,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	ValidatingCarrier string                 `protobuf:"bytes,5,opt,name=validating_carrier,json=validatingCarrier,proto3" json:"validating_carrier,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_internal_adapters_protobuf_trips_trips_proto_rawDescGZIP(), []int{6}
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Provider) GetGds() string {
	if x != nil {
		return x.Gds
	}
	return ""
}

func (x *Provider) GetGdsServer() string {
	if x != nil {
		return x.GdsServer
	}
	return ""
}

func (x *Provider) GetOfficeId() string {
	if x != nil {
		return x.OfficeId
	}
	return ""
}

func (x *Provider) GetValidatingCarrier() string {
	if x != nil {
		return x.ValidatingCarrier
	}
	return ""
}

type FareRules struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsRefund       bool                   `protobuf:"varint,1,opt,name=is_refund,json=isRefund,proto3" json:"is_refund,omitempty"`
	IsExchangeable bool                   `protobuf:"varint,2,opt,name=is_exchangeable,json=isExchangeable,proto3" json:"is_exchangeable,omitempty"`
	RefundAmount   float64                `protobuf:"fixed64,3,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	ExchangeFee    float64                `protobuf:"fixed64,4,opt,name=exchange_fee,json=exchangeFee,proto3" json:"exchange_fee,omitempty"`
	Penalty        float64                `protobuf:"fixed64,5,opt,name=penalty,proto3" json:"penalty,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FareRules) Reset() {
	*x = FareRules{}
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FareRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FareRules) ProtoMessage() {}

func (x *FareRules) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FareRules.ProtoReflect.Descriptor instead.
func (*FareRules) Descriptor() ([]byte, []int) {
	return file_internal_adapters_protobuf_trips_trips_proto_rawDescGZIP(), []int{7}
}

func (x *FareRules) GetIsRefund() bool {
	if x != nil {
		return x.IsRefund
	}
	return false
}

func (x *FareRules) GetIsExchangeable() bool {
	if x != nil {
		return x.IsExchangeable
	}
	return false
}

func (x *FareRules) GetRefundAmount() float64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

func (x *FareRules) GetExchangeFee() float64 {
	if x != nil {
		return x.ExchangeFee
	}
	return 0
}

func (x *FareRules) GetPenalty() float64 {
	if x != nil {
		return x.Penalty
	}
	return 0
}

type TripMetadata struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FlightType         string                 `protobuf:"bytes,1,opt,name=flight_type,json=flightType,proto3" json:"flight_type,omitempty"`
	IsVtrip            bool                   `protobuf:"varint,2,opt,name=is_vtrip,json=isVtrip,proto3" json:"is_vtrip,omitempty"`
	VtripComboId       string                 `protobuf:"bytes,3,opt,name=vtrip_combo_id,json=vtripComboId,proto3" json:"vtrip_combo_id,omitempty"`
	RouteDuration      int32                  `protobuf:"varint,4,opt,name=route_duration,json=routeDuration,proto3" json:"route_duration,omitempty"`
	NumTransfers       int32                  `protobuf:"varint,5,opt,name=num_transfers,json=numTransfers,proto3" json:"num_transfers,omitempty"`
	HasBaggage         bool                   `protobuf:"varint,6,opt,name=has_baggage,json=hasBaggage,proto3" json:"has_baggage,omitempty"`
	HasLuggage         bool                   `protobuf:"varint,7,opt,name=has_luggage,json=hasLuggage,proto3" json:"has_luggage,omitempty"`
	FareFamily         *FareFamily            `protobuf:"bytes,8,opt,name=fare_family,json=fareFamily,proto3" json:"fare_family,omitempty"`
	TariffType         string                 `protobuf:"bytes,9,opt,name=tariff_type,json=tariffType,proto3" json:"tariff_type,omitempty"`
	AgeThreshold       int32                  `protobuf:"varint,10,opt,name=age_threshold,json=ageThreshold,proto3" json:"age_threshold,omitempty"`
	IsVirtualInterline bool                   `protobuf:"varint,11,opt,name=is_virtual_interline,json=isVirtualInterline,proto3" json:"is_virtual_interline,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TripMetadata) Reset() {
	*x = TripMetadata{}
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripMetadata) ProtoMessage() {}

func (x *TripMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripMetadata.ProtoReflect.Descriptor instead.
func (*TripMetadata) Descriptor() ([]byte, []int) {
	return file_internal_adapters_protobuf_trips_trips_proto_rawDescGZIP(), []int{8}
}

func (x *TripMetadata) GetFlightType() string {
	if x != nil {
		return x.FlightType
	}
	return ""
}

func (x *TripMetadata) GetIsVtrip() bool {
	if x != nil {
		return x.IsVtrip
	}
	return false
}

func (x *TripMetadata) GetVtripComboId() string {
	if x != nil {
		return x.VtripComboId
	}
	return ""
}

func (x *TripMetadata) GetRouteDuration() int32 {
	if x != nil {
		return x.RouteDuration
	}
	return 0
}

func (x *TripMetadata) GetNumTransfers() int32 {
	if x != nil {
		return x.NumTransfers
	}
	return 0
}

func (x *TripMetadata) GetHasBaggage() bool {
	if x != nil {
		return x.HasBaggage
	}
	return false
}

func (x *TripMetadata) GetHasLuggage() bool {
	if x != nil {
		return x.HasLuggage
	}
	return false
}

func (x *TripMetadata) GetFareFamily() *FareFamily {
	if x != nil {
		return x.FareFamily
	}
	return nil
}

func (x *TripMetadata) GetTariffType() string {
	if x != nil {
		return x.TariffType
	}
	return ""
}

func (x *TripMetadata) GetAgeThreshold() int32 {
	if x != nil {
		return x.AgeThreshold
	}
	return 0
}

func (x *TripMetadata) GetIsVirtualInterline() bool {
	if x != nil {
		return x.IsVirtualInterline
	}
	return false
}

type FareFamily struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MarketingName string                 `protobuf:"bytes,3,opt,name=marketing_name,json=marketingName,proto3" json:"marketing_name,omitempty"`
	HasFareFamily bool                   `protobuf:"varint,4,opt,name=has_fare_family,json=hasFareFamily,proto3" json:"has_fare_family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FareFamily) Reset() {
	*x = FareFamily{}
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FareFamily) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FareFamily) ProtoMessage() {}

func (x *FareFamily) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FareFamily.ProtoReflect.Descriptor instead.
func (*FareFamily) Descriptor() ([]byte, []int) {
	return file_internal_adapters_protobuf_trips_trips_proto_rawDescGZIP(), []int{9}
}

func (x *FareFamily) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FareFamily) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FareFamily) GetMarketingName() string {
	if x != nil {
		return x.MarketingName
	}
	return ""
}

func (x *FareFamily) GetHasFareFamily() bool {
	if x != nil {
		return x.HasFareFamily
	}
	return false
}

type TripBooking struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	ExpiresAt                     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	TicketingTimeLimit            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ticketing_time_limit,json=ticketingTimeLimit,proto3" json:"ticketing_time_limit,omitempty"`
	ProviderRecommendationLimit   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=provider_recommendation_limit,json=providerRecommendationLimit,proto3" json:"provider_recommendation_limit,omitempty"`
	ProviderRecommendationCreated *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=provider_recommendation_created,json=providerRecommendationCreated,proto3" json:"provider_recommendation_created,omitempty"`
	CountOfBlanks                 int32                  `protobuf:"varint,5,opt,name=count_of_blanks,json=countOfBlanks,proto3" json:"count_of_blanks,omitempty"`
	BookingWithPartialDataAllowed bool                   `protobuf:"varint,6,opt,name=booking_with_partial_data_allowed,json=bookingWithPartialDataAllowed,proto3" json:"booking_with_partial_data_allowed,omitempty"`
	BookingActualizationAllowed   bool                   `protobuf:"varint,7,opt,name=booking_actualization_allowed,json=bookingActualizationAllowed,proto3" json:"booking_actualization_allowed,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *TripBooking) Reset() {
	*x = TripBooking{}
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripBooking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripBooking) ProtoMessage() {}

func (x *TripBooking) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripBooking.ProtoReflect.Descriptor instead.
func (*TripBooking) Descriptor() ([]byte, []int) {
	return file_internal_adapters_protobuf_trips_trips_proto_rawDescGZIP(), []int{10}
}

func (x *TripBooking) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *TripBooking) GetTicketingTimeLimit() *timestamppb.Timestamp {
	if x != nil {
		return x.TicketingTimeLimit
	}
	return nil
}

func (x *TripBooking) GetProviderRecommendationLimit() *timestamppb.Timestamp {
	if x != nil {
		return x.ProviderRecommendationLimit
	}
	return nil
}

func (x *TripBooking) GetProviderRecommendationCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.ProviderRecommendationCreated
	}
	return nil
}

func (x *TripBooking) GetCountOfBlanks() int32 {
	if x != nil {
		return x.CountOfBlanks
	}
	return 0
}

func (x *TripBooking) GetBookingWithPartialDataAllowed() bool {
	if x != nil {
		return x.BookingWithPartialDataAllowed
	}
	return false
}

func (x *TripBooking) GetBookingActualizationAllowed() bool {
	if x != nil {
		return x.BookingActualizationAllowed
	}
	return false
}

type Trips struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trips         []*Trip                `protobuf:"bytes,1,rep,name=trips,proto3" json:"trips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trips) Reset() {
	*x = Trips{}
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trips) ProtoMessage() {}

func (x *Trips) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_protobuf_trips_trips_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trips.ProtoReflect.Descriptor instead.
func (*Trips) Descriptor() ([]byte, []int) {
	return file_internal_adapters_protobuf_trips_trips_proto_rawDescGZIP(), []int{11}
}

func (x *Trips) GetTrips() []*Trip {
	if x != nil {
		return x.Trips
	}
	return nil
}

var File_internal_adapters_protobuf_trips_trips_proto protoreflect.FileDescriptor

const file_internal_adapters_protobuf_trips_trips_proto_rawDesc = "" +
	"\n" +
	",internal/adapters/protobuf/trips/trips.proto\x12\x05trips\x1a\x1fgoogle/protobuf/timestamp.proto\x1a(internal/adapters/protobuf/sro/sro.proto\"\x82\x03\n" +
	"\x04Trip\x12\x10\n" +
	"\x03rid\x18\x01 \x01(\tR\x03rid\x12\x10\n" +
	"\x03tid\x18\x02 \x01(\tR\x03tid\x12\x10\n" +
	"\x03sid\x18\x03 \x01(\tR\x03sid\x12\x19\n" +
	"\bcache_id\x18\x04 \x01(\tR\acacheId\x12+\n" +
	"\bprovider\x18\x05 \x01(\v2\x0f.trips.ProviderR\bprovider\x12.\n" +
	"\bsegments\x18\x06 \x03(\v2\x12.trips.TripSegmentR\bsegments\x12)\n" +
	"\x06prices\x18\a \x01(\v2\x11.trips.TripPricesR\x06prices\x12&\n" +
	"\x05rules\x18\b \x01(\v2\x10.trips.FareRulesR\x05rules\x12/\n" +
	"\bmetadata\x18\t \x01(\v2\x13.trips.TripMetadataR\bmetadata\x12,\n" +
	"\abooking\x18\n" +
	" \x01(\v2\x12.trips.TripBookingR\abooking\x12\x1a\n" +
	"\x03sro\x18\v \x01(\v2\b.sro.SROR\x03sro\"\xea\x03\n" +
	"\vTripSegment\x12#\n" +
	"\rflight_number\x18\x01 \x01(\tR\fflightNumber\x12\x18\n" +
	"\acarrier\x18\x02 \x01(\tR\acarrier\x12+\n" +
	"\x11operating_carrier\x18\x03 \x01(\tR\x10operatingCarrier\x120\n" +
	"\tdeparture\x18\x04 \x01(\v2\x12.trips.FlightPointR\tdeparture\x12,\n" +
	"\aarrival\x18\x05 \x01(\v2\x12.trips.FlightPointR\aarrival\x12)\n" +
	"\x10duration_minutes\x18\x06 \x01(\x05R\x0fdurationMinutes\x12\x1f\n" +
	"\vcabin_class\x18\a \x01(\tR\n" +
	"cabinClass\x12\x1b\n" +
	"\tfare_code\x18\b \x01(\tR\bfareCode\x12,\n" +
	"\abaggage\x18\t \x01(\v2\x12.trips.BaggageInfoR\abaggage\x12\x12\n" +
	"\x04meal\x18\n" +
	" \x01(\tR\x04meal\x12\x1a\n" +
	"\baircraft\x18\v \x01(\tR\baircraft\x12*\n" +
	"\x11stop_time_minutes\x18\f \x01(\x05R\x0fstopTimeMinutes\x12\x1c\n" +
	"\tdirection\x18\r \x01(\x05R\tdirection\"s\n" +
	"\vFlightPoint\x12\x18\n" +
	"\aairport\x18\x01 \x01(\tR\aairport\x12\x1a\n" +
	"\bterminal\x18\x02 \x01(\tR\bterminal\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"Q\n" +
	"\vBaggageInfo\x12\x16\n" +
	"\x06pieces\x18\x01 \x01(\x05R\x06pieces\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xe2\x04\n" +
	"\n" +
	"TripPrices\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12!\n" +
	"\fsearch_price\x18\x02 \x01(\x01R\vsearchPrice\x12\x1d\n" +
	"\n" +
	"price_fare\x18\x03 \x01(\x01R\tpriceFare\x120\n" +
	"\x14provider_service_fee\x18\x04 \x01(\x01R\x12providerServiceFee\x122\n" +
	"\x15provider_taxes_amount\x18\x05 \x01(\x01R\x13providerTaxesAmount\x12+\n" +
	"\x11provider_currency\x18\x06 \x01(\tR\x10providerCurrency\x12.\n" +
	"\x13min_allowable_price\x18\a \x01(\x01R\x11minAllowablePrice\x12\x17\n" +
	"\atkp_tax\x18\b \x01(\x01R\x06tkpTax\x12\x19\n" +
	"\bspec_tax\x18\t \x01(\x01R\aspecTax\x122\n" +
	"\vpricer_info\x18\n" +
	" \x01(\v2\x11.trips.PricerInfoR\n" +
	"pricerInfo\x12\x1d\n" +
	"\n" +
	"bags_price\x18\v \x01(\x01R\tbagsPrice\x12g\n" +
	"\x18passengers_price_details\x18\f \x03(\v2-.trips.TripPrices.PassengersPriceDetailsEntryR\x16passengersPriceDetails\x1aI\n" +
	"\x1bPassengersPriceDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x9d\x01\n" +
	"\n" +
	"PricerInfo\x12\x16\n" +
	"\x06markup\x18\x01 \x01(\x01R\x06markup\x12\x1e\n" +
	"\n" +
	"commission\x18\x02 \x01(\x01R\n" +
	"commission\x122\n" +
	"\x15partner_affiliate_fee\x18\x03 \x01(\x01R\x13partnerAffiliateFee\x12#\n" +
	"\rcashback_rate\x18\x04 \x01(\x01R\fcashbackRate\"\x9b\x01\n" +
	"\bProvider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03gds\x18\x02 \x01(\tR\x03gds\x12\x1d\n" +
	"\n" +
	"gds_server\x18\x03 \x01(\tR\tgdsServer\x12\x1b\n" +
	"\toffice_id\x18\x04 \x01(\tR\bofficeId\x12-\n" +
	"\x12validating_carrier\x18\x05 \x01(\tR\x11validatingCarrier\"\xb3\x01\n" +
	"\tFareRules\x12\x1b\n" +
	"\tis_refund\x18\x01 \x01(\bR\bisRefund\x12'\n" +
	"\x0fis_exchangeable\x18\x02 \x01(\bR\x0eisExchangeable\x12#\n" +
	"\rrefund_amount\x18\x03 \x01(\x01R\frefundAmount\x12!\n" +
	"\fexchange_fee\x18\x04 \x01(\x01R\vexchangeFee\x12\x18\n" +
	"\apenalty\x18\x05 \x01(\x01R\apenalty\"\xaa\x03\n" +
	"\fTripMetadata\x12\x1f\n" +
	"\vflight_type\x18\x01 \x01(\tR\n" +
	"flightType\x12\x19\n" +
	"\bis_vtrip\x18\x02 \x01(\bR\aisVtrip\x12$\n" +
	"\x0evtrip_combo_id\x18\x03 \x01(\tR\fvtripComboId\x12%\n" +
	"\x0eroute_duration\x18\x04 \x01(\x05R\rrouteDuration\x12#\n" +
	"\rnum_transfers\x18\x05 \x01(\x05R\fnumTransfers\x12\x1f\n" +
	"\vhas_baggage\x18\x06 \x01(\bR\n" +
	"hasBaggage\x12\x1f\n" +
	"\vhas_luggage\x18\a \x01(\bR\n" +
	"hasLuggage\x122\n" +
	"\vfare_family\x18\b \x01(\v2\x11.trips.FareFamilyR\n" +
	"fareFamily\x12\x1f\n" +
	"\vtariff_type\x18\t \x01(\tR\n" +
	"tariffType\x12#\n" +
	"\rage_threshold\x18\n" +
	" \x01(\x05R\fageThreshold\x120\n" +
	"\x14is_virtual_interline\x18\v \x01(\bR\x12isVirtualInterline\"\x83\x01\n" +
	"\n" +
	"FareFamily\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0emarketing_name\x18\x03 \x01(\tR\rmarketingName\x12&\n" +
	"\x0fhas_fare_family\x18\x04 \x01(\bR\rhasFareFamily\"\x90\x04\n" +
	"\vTripBooking\x129\n" +
	"\n" +
	"expires_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12L\n" +
	"\x14ticketing_time_limit\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x12ticketingTimeLimit\x12^\n" +
	"\x1dprovider_recommendation_limit\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x1bproviderRecommendationLimit\x12b\n" +
	"\x1fprovider_recommendation_created\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x1dproviderRecommendationCreated\x12&\n" +
	"\x0fcount_of_blanks\x18\x05 \x01(\x05R\rcountOfBlanks\x12H\n" +
	"!booking_with_partial_data_allowed\x18\x06 \x01(\bR\x1dbookingWithPartialDataAllowed\x12B\n" +
	"\x1dbooking_actualization_allowed\x18\a \x01(\bR\x1bbookingActualizationAllowed\"*\n" +
	"\x05Trips\x12!\n" +
	"\x05trips\x18\x01 \x03(\v2\v.trips.TripR\x05tripsBHZFgithub.com/de4et/flight-booking/internal/adapters/protobuf/trips;tripsb\x06proto3"

var (
	file_internal_adapters_protobuf_trips_trips_proto_rawDescOnce sync.Once
	file_internal_adapters_protobuf_trips_trips_proto_rawDescData []byte
)

func file_internal_adapters_protobuf_trips_trips_proto_rawDescGZIP() []byte {
	file_internal_adapters_protobuf_trips_trips_proto_rawDescOnce.Do(func() {
		file_internal_adapters_protobuf_trips_trips_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_adapters_protobuf_trips_trips_proto_rawDesc), len(file_internal_adapters_protobuf_trips_trips_proto_rawDesc)))
	})
	return file_internal_adapters_protobuf_trips_trips_proto_rawDescData
}

var (
	file_internal_adapters_protobuf_trips_trips_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
	file_internal_adapters_protobuf_trips_trips_proto_goTypes  = []any{
		(*Trip)(nil),                  // 0: trips.Trip
		(*TripSegment)(nil),           // 1: trips.TripSegment
		(*FlightPoint)(nil),           // 2: trips.FlightPoint
		(*BaggageInfo)(nil),           // 3: trips.BaggageInfo
		(*TripPrices)(nil),            // 4: trips.TripPrices
		(*PricerInfo)(nil),            // 5: trips.PricerInfo
		(*Provider)(nil),              // 6: trips.Provider
		(*FareRules)(nil),             // 7: trips.FareRules
		(*TripMetadata)(nil),          // 8: trips.TripMetadata
		(*FareFamily)(nil),            // 9: trips.FareFamily
		(*TripBooking)(nil),           // 10: trips.TripBooking
		(*Trips)(nil),                 // 11: trips.Trips
		nil,                           // 12: trips.TripPrices.PassengersPriceDetailsEntry
		(*sro.SRO)(nil),               // 13: sro.SRO
		(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	}
)

var file_internal_adapters_protobuf_trips_trips_proto_depIdxs = []int32{
	6,  // 0: trips.Trip.provider:type_name -> trips.Provider
	1,  // 1: trips.Trip.segments:type_name -> trips.TripSegment
	4,  // 2: trips.Trip.prices:type_name -> trips.TripPrices
	7,  // 3: trips.Trip.rules:type_name -> trips.FareRules
	8,  // 4: trips.Trip.metadata:type_name -> trips.TripMetadata
	10, // 5: trips.Trip.booking:type_name -> trips.TripBooking
	13, // 6: trips.Trip.sro:type_name -> sro.SRO
	2,  // 7: trips.TripSegment.departure:type_name -> trips.FlightPoint
	2,  // 8: trips.TripSegment.arrival:type_name -> trips.FlightPoint
	3,  // 9: trips.TripSegment.baggage:type_name -> trips.BaggageInfo
	14, // 10: trips.FlightPoint.time:type_name -> google.protobuf.Timestamp
	5,  // 11: trips.TripPrices.pricer_info:type_name -> trips.PricerInfo
	12, // 12: trips.TripPrices.passengers_price_details:type_name -> trips.TripPrices.PassengersPriceDetailsEntry
	9,  // 13: trips.TripMetadata.fare_family:type_name -> trips.FareFamily
	14, // 14: trips.TripBooking.expires_at:type_name -> google.protobuf.Timestamp
	14, // 15: trips.TripBooking.ticketing_time_limit:type_name -> google.protobuf.Timestamp
	14, // 16: trips.TripBooking.provider_recommendation_limit:type_name -> google.protobuf.Timestamp
	14, // 17: trips.TripBooking.provider_recommendation_created:type_name -> google.protobuf.Timestamp
	0,  // 18: trips.Trips.trips:type_name -> trips.Trip
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_internal_adapters_protobuf_trips_trips_proto_init() }
func file_internal_adapters_protobuf_trips_trips_proto_init() {
	if File_internal_adapters_protobuf_trips_trips_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_adapters_protobuf_trips_trips_proto_rawDesc), len(file_internal_adapters_protobuf_trips_trips_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_adapters_protobuf_trips_trips_proto_goTypes,
		DependencyIndexes: file_internal_adapters_protobuf_trips_trips_proto_depIdxs,
		MessageInfos:      file_internal_adapters_protobuf_trips_trips_proto_msgTypes,
	}.Build()
	File_internal_adapters_protobuf_trips_trips_proto = out.File
	file_internal_adapters_protobuf_trips_trips_proto_goTypes = nil
	file_internal_adapters_protobuf_trips_trips_proto_depIdxs = nil
}
