// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: sro.proto

package sro

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SRO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*Segment             `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	Passengers    *Passengers            `protobuf:"bytes,2,opt,name=passengers,proto3" json:"passengers,omitempty"`
	Class         string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ChannelToken  *ChannelToken          `protobuf:"bytes,5,opt,name=channel_token,json=channelToken,proto3" json:"channel_token,omitempty"`
	Filters       *Filters               `protobuf:"bytes,6,opt,name=filters,proto3" json:"filters,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRO) Reset() {
	*x = SRO{}
	mi := &file_sro_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRO) ProtoMessage() {}

func (x *SRO) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRO.ProtoReflect.Descriptor instead.
func (*SRO) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{0}
}

func (x *SRO) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *SRO) GetPassengers() *Passengers {
	if x != nil {
		return x.Passengers
	}
	return nil
}

func (x *SRO) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *SRO) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SRO) GetChannelToken() *ChannelToken {
	if x != nil {
		return x.ChannelToken
	}
	return nil
}

func (x *SRO) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SRO) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Segment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_sro_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{1}
}

func (x *Segment) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Segment) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Segment) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type Passengers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Adt           int32                  `protobuf:"varint,1,opt,name=adt,proto3" json:"adt,omitempty"`
	Chd           int32                  `protobuf:"varint,2,opt,name=chd,proto3" json:"chd,omitempty"`
	Inf           int32                  `protobuf:"varint,3,opt,name=inf,proto3" json:"inf,omitempty"`
	Src           int32                  `protobuf:"varint,4,opt,name=src,proto3" json:"src,omitempty"`
	Yth           int32                  `protobuf:"varint,5,opt,name=yth,proto3" json:"yth,omitempty"`
	Ins           bool                   `protobuf:"varint,6,opt,name=ins,proto3" json:"ins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Passengers) Reset() {
	*x = Passengers{}
	mi := &file_sro_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Passengers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Passengers) ProtoMessage() {}

func (x *Passengers) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Passengers.ProtoReflect.Descriptor instead.
func (*Passengers) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{2}
}

func (x *Passengers) GetAdt() int32 {
	if x != nil {
		return x.Adt
	}
	return 0
}

func (x *Passengers) GetChd() int32 {
	if x != nil {
		return x.Chd
	}
	return 0
}

func (x *Passengers) GetInf() int32 {
	if x != nil {
		return x.Inf
	}
	return 0
}

func (x *Passengers) GetSrc() int32 {
	if x != nil {
		return x.Src
	}
	return 0
}

func (x *Passengers) GetYth() int32 {
	if x != nil {
		return x.Yth
	}
	return 0
}

func (x *Passengers) GetIns() bool {
	if x != nil {
		return x.Ins
	}
	return false
}

type ChannelToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartnerCode   string                 `protobuf:"bytes,1,opt,name=partner_code,json=partnerCode,proto3" json:"partner_code,omitempty"`
	SourceCode    string                 `protobuf:"bytes,2,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelToken) Reset() {
	*x = ChannelToken{}
	mi := &file_sro_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelToken) ProtoMessage() {}

func (x *ChannelToken) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelToken.ProtoReflect.Descriptor instead.
func (*ChannelToken) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelToken) GetPartnerCode() string {
	if x != nil {
		return x.PartnerCode
	}
	return ""
}

func (x *ChannelToken) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

type Filters struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsDirectOnly    bool                   `protobuf:"varint,1,opt,name=is_direct_only,json=isDirectOnly,proto3" json:"is_direct_only,omitempty"`
	MaxStops        int32                  `protobuf:"varint,2,opt,name=max_stops,json=maxStops,proto3" json:"max_stops,omitempty"`
	WithBaggageOnly bool                   `protobuf:"varint,3,opt,name=with_baggage_only,json=withBaggageOnly,proto3" json:"with_baggage_only,omitempty"`
	Carriers        []string               `protobuf:"bytes,4,rep,name=carriers,proto3" json:"carriers,omitempty"`
	CarriersType    string                 `protobuf:"bytes,5,opt,name=carriers_type,json=carriersType,proto3" json:"carriers_type,omitempty"`
	GdsList         []string               `protobuf:"bytes,6,rep,name=gds_list,json=gdsList,proto3" json:"gds_list,omitempty"`
	GdsListType     string                 `protobuf:"bytes,7,opt,name=gds_list_type,json=gdsListType,proto3" json:"gds_list_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Filters) Reset() {
	*x = Filters{}
	mi := &file_sro_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{4}
}

func (x *Filters) GetIsDirectOnly() bool {
	if x != nil {
		return x.IsDirectOnly
	}
	return false
}

func (x *Filters) GetMaxStops() int32 {
	if x != nil {
		return x.MaxStops
	}
	return 0
}

func (x *Filters) GetWithBaggageOnly() bool {
	if x != nil {
		return x.WithBaggageOnly
	}
	return false
}

func (x *Filters) GetCarriers() []string {
	if x != nil {
		return x.Carriers
	}
	return nil
}

func (x *Filters) GetCarriersType() string {
	if x != nil {
		return x.CarriersType
	}
	return ""
}

func (x *Filters) GetGdsList() []string {
	if x != nil {
		return x.GdsList
	}
	return nil
}

func (x *Filters) GetGdsListType() string {
	if x != nil {
		return x.GdsListType
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsTest        bool                   `protobuf:"varint,1,opt,name=is_test,json=isTest,proto3" json:"is_test,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Timeout       int32                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_sro_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_sro_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_sro_proto_rawDescGZIP(), []int{5}
}

func (x *Metadata) GetIsTest() bool {
	if x != nil {
		return x.IsTest
	}
	return false
}

func (x *Metadata) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Metadata) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Metadata) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

var File_sro_proto protoreflect.FileDescriptor

const file_sro_proto_rawDesc = "" +
	"\n" +
	"\tsro.proto\x12\x03sro\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x02\n" +
	"\x03SRO\x12(\n" +
	"\bsegments\x18\x01 \x03(\v2\f.sro.SegmentR\bsegments\x12/\n" +
	"\n" +
	"passengers\x18\x02 \x01(\v2\x0f.sro.PassengersR\n" +
	"passengers\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x126\n" +
	"\rchannel_token\x18\x05 \x01(\v2\x11.sro.ChannelTokenR\fchannelToken\x12&\n" +
	"\afilters\x18\x06 \x01(\v2\f.sro.FiltersR\afilters\x12)\n" +
	"\bmetadata\x18\a \x01(\v2\r.sro.MetadataR\bmetadata\"]\n" +
	"\aSegment\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12.\n" +
	"\x04date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"x\n" +
	"\n" +
	"Passengers\x12\x10\n" +
	"\x03adt\x18\x01 \x01(\x05R\x03adt\x12\x10\n" +
	"\x03chd\x18\x02 \x01(\x05R\x03chd\x12\x10\n" +
	"\x03inf\x18\x03 \x01(\x05R\x03inf\x12\x10\n" +
	"\x03src\x18\x04 \x01(\x05R\x03src\x12\x10\n" +
	"\x03yth\x18\x05 \x01(\x05R\x03yth\x12\x10\n" +
	"\x03ins\x18\x06 \x01(\bR\x03ins\"R\n" +
	"\fChannelToken\x12!\n" +
	"\fpartner_code\x18\x01 \x01(\tR\vpartnerCode\x12\x1f\n" +
	"\vsource_code\x18\x02 \x01(\tR\n" +
	"sourceCode\"\xf8\x01\n" +
	"\aFilters\x12$\n" +
	"\x0eis_direct_only\x18\x01 \x01(\bR\fisDirectOnly\x12\x1b\n" +
	"\tmax_stops\x18\x02 \x01(\x05R\bmaxStops\x12*\n" +
	"\x11with_baggage_only\x18\x03 \x01(\bR\x0fwithBaggageOnly\x12\x1a\n" +
	"\bcarriers\x18\x04 \x03(\tR\bcarriers\x12#\n" +
	"\rcarriers_type\x18\x05 \x01(\tR\fcarriersType\x12\x19\n" +
	"\bgds_list\x18\x06 \x03(\tR\agdsList\x12\"\n" +
	"\rgds_list_type\x18\a \x01(\tR\vgdsListType\"u\n" +
	"\bMetadata\x12\x17\n" +
	"\ais_test\x18\x01 \x01(\bR\x06isTest\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeoutBDZBgithub.com/de4et/flight-booking/internal/adapters/protobuf/sro;srob\x06proto3"

var (
	file_sro_proto_rawDescOnce sync.Once
	file_sro_proto_rawDescData []byte
)

func file_sro_proto_rawDescGZIP() []byte {
	file_sro_proto_rawDescOnce.Do(func() {
		file_sro_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sro_proto_rawDesc), len(file_sro_proto_rawDesc)))
	})
	return file_sro_proto_rawDescData
}

var (
	file_sro_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
	file_sro_proto_goTypes  = []any{
		(*SRO)(nil),                   // 0: sro.SRO
		(*Segment)(nil),               // 1: sro.Segment
		(*Passengers)(nil),            // 2: sro.Passengers
		(*ChannelToken)(nil),          // 3: sro.ChannelToken
		(*Filters)(nil),               // 4: sro.Filters
		(*Metadata)(nil),              // 5: sro.Metadata
		(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	}
)
var file_sro_proto_depIdxs = []int32{
	1, // 0: sro.SRO.segments:type_name -> sro.Segment
	2, // 1: sro.SRO.passengers:type_name -> sro.Passengers
	3, // 2: sro.SRO.channel_token:type_name -> sro.ChannelToken
	4, // 3: sro.SRO.filters:type_name -> sro.Filters
	5, // 4: sro.SRO.metadata:type_name -> sro.Metadata
	6, // 5: sro.Segment.date:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sro_proto_init() }
func file_sro_proto_init() {
	if File_sro_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sro_proto_rawDesc), len(file_sro_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sro_proto_goTypes,
		DependencyIndexes: file_sro_proto_depIdxs,
		MessageInfos:      file_sro_proto_msgTypes,
	}.Build()
	File_sro_proto = out.File
	file_sro_proto_goTypes = nil
	file_sro_proto_depIdxs = nil
}
